version: "3"
services:
    gvm:
        image: netizensoc/gvm-scanner:dev
        volumes:
          - gvm-data:/data
        environment:
          - USERNAME="admin"
          - PASSWORD="admin"
          - RELAYHOST="smtp"
          - SMTPPORT=25
          - AUTO_SYNC=true
          - HTTPS=true
          - TZ="ETC"
          - SSHD=false
          - DB_PASSWORD="none"
        ports:
          - "443:9392"  # Web interface
          - "5432:5432" # Access PostgreSQL database from external tools
          - "2222:22"   # SSH for remote sensors
        restart: unless-stopped
volumes:
    gvm-data:
